example.property: "I AM A PROD PROPERTY OVERRIDE"
spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.mysql.Driver"
spring.datasource.url: jdbc:mysql://db-warm-micro.c8bsxpdjb1j7.ap-northeast-2.rds.amazonaws.com:3306/practice
spring.datasource.username: "admin"
spring.datasource.password: "35734364183345d9a9a4238302fd099caa3151bd0ee59fb5d445c2e183ed0c29"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"