example:
  property: "I AM IN THE ORGANIZATION DEFAULT"
server:
  port: 8085
spring:
  jpa:
    database: "MYSQL"
    show-sql: "false"
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        # dialect: "org.hibernate.dialect.MySQLDialect"
        ddl-auto: "update"
  datasource:
    platform:  "mysql"
    url: jdbc:mysql://jinho-db.crrywx8kuivs.ap-northeast-2.rds.amazonaws.com:3306/jinho
    username: "admin"
    password: "{cipher}749244292eb7740fa7d9674d0386fcc4b7f37a2885bf9c4f286a422b07c7e2ef"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "org.mysql.Driver"
redis:
  server: "redis"
  port: "6379"
signing:
  key: "345345fsdfsf5345"