server:
    port: 8888
spring:
    cloud:
        config:
            server:
                git:
                    default-label: main
                    uri: https://github.com/zzzinho/spring-msa
                    searchPaths: config/licensingservice, config/organizationservice
                    # username: native-cloud-apps
                    # password: 0ffended
                encrypt.enabled: false