server:
    port: 8888
spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    searchLocations: file:///Users/jeongjinho/vscode/SpringMSA/confsvr/src/main/resources/config/licensingservice
                    
