server:
    port: 8888
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/zzzinho/spring-msa
                    searchPaths: licensingservice,organizationservice
                    # username: native-cloud-apps
                    # password: 0ffended